### ISSUE TITLE
Straw golem mod crashes server (fabric 1.19)

### ISSUE THREAD

**Issue by Super1166** [t2pellet/strawgolem#101]
So i have a modpack on my fabric 1.19 server and when the straw golem mod is in the server crashes after a bit. i deleted the mod and there was no crashes so far. i would like to know if theres a certain mod that is incompatible with the straw golem. here's a screenshot of my modpack:
![Screenshot_769](https://user-images.githubusercontent.com/110970817/183983840-60837000-fc8f-437e-8861-6110ba3e1c73.png)
:

**Comment by t2pellet** [comment]
should be fixed in newest release
