### ISSUE TITLE
Strawgolem-forge-1.19-2.0.0b1 crashes without crash log on 1.19 forge 41.1.0

### ISSUE THREAD

**Issue by babacon88** [t2pellet/strawgolem#102]
**Game Info**
Game Version :1.19
Mod Version :forge-1.19-2.0.0b1
Mod Loader :forge 14.1.0

**Describe the bug**
it crashes on start up
there is no crash log, it was difficult for me to pin point this mod

**Comment by t2pellet** [comment]
Should be fixed in newest release
