### ISSUE TITLE
crash before starting the server

### ISSUE THREAD

**Issue by mraxg** [t2pellet/strawgolem#104]
**Game Info**
Game Version : 1.18.2
Mod Version : 2.0.0
Mod Loader : mohist

**Describe the bug**
Hi, it's just this error and I can't fix it. 
during firing event: Cannot invoke "com.t2pellet.strawgolem.storage.StrawgolemSaveData.saveData(net.minecraft.server.MinecraftServer)" because "com.t2pellet.strawgolem.StrawgolemCommon.data" is null

**To Reproduce**

2. Click on '.....'

**Screenshots**
![image](https://user-images.githubusercontent.com/111460420/185233721-5d0282e8-669d-4814-a074-b13c57b6565b.png)

**Additional context**
The server is hosted in my pc, and is powered by mohist, but i'm not using any plugins

**Comment by t2pellet** [comment]
Should be fixed in newest curseforge upload
