### ISSUE TITLE
[1.18.2] - Server Crash (Attempting to insert point outside of boundary)

### ISSUE THREAD

**Issue by aking4125** [t2pellet/strawgolem#106]
**Game Info**
Game Version : 1.18.2
Mod Version : [strawgolem-1.18.2-2.0.0b2](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/3973284)
Mod Loader : Forge 40.1.80

**Describe the bug**
After sometime, with the golems present or not. The server crashes with the following crash report. [crash-2022-09-11_12.14.12-server.txt](https://github.com/t2pellet/strawgolem/files/9543046/crash-2022-09-11_12.14.12-server.txt)

**Comment by Vashal0** [comment]
I also experienced this crash

Game Info
Game Version : 1.18.2
Mod Version : [strawgolem-1.18.2-2.0.0b2](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/3973284)
Mod Loader : Forge 40.1.80

Describe the bug
My crash happened about 30 seconds after using a sprinkler from Create: Slice and Dice. Here is the crash report: 
[crash-2022-10-02_04.28.14-server.txt](https://github.com/t2pellet/strawgolem/files/9692335/crash-2022-10-02_04.28.14-server.txt)

**Comment by James00Games** [comment]
:(  
Add me to this crash report
Wasn't my ram allocation or CPU usage.
Macbook Pro, 13 inch 2020,
2.3GHz quad-core Intel Core i7, Turbo Boost up to 4.1GHz, with 8MB shared L3 cache
32GB of 3733MHz LPDDR4X memory

[latest.log](https://github.com/t2pellet/strawgolem/files/9712067/latest.log)

**Comment by CaptainPepperjack** [comment]
Same crash

Game Info
Game Version : 1.18.2
Mod Version : [strawgolem-1.18.2-2.0.0b2](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/3973284)
Mod Loader : Forge 40.1.80
[crash-2022-10-12_14.37.42-server.txt](https://github.com/t2pellet/strawgolem/files/9767858/crash-2022-10-12_14.37.42-server.txt)

**Comment by spudnut2000** [comment]
Yep, same crash here. I can't seem to replicate it as it just happens at random, but it crashed about 5 times within an hour.

Game Info:
Game Version: 1.18.2
Mod Version: strawgolem-1.18.2-2.0.0b2
Mod Loader: Forge 40.1.80
 
[straw-golem-crash-report.txt](https://github.com/t2pellet/strawgolem/files/10042197/straw-golem-crash-report.txt)
