### ISSUE TITLE
[1.19.2-43.1.2 Forge] StrawGolem crashes at game startup trying to load non-existent class

### ISSUE THREAD

**Issue by TelepathicGrunt** [t2pellet/strawgolem#107]
I am using only 1.19-2.0.0b2 StrawGolem mod alone with no other mods on 1.19.2 MC and 43.1.2 Forge. 
![image](https://user-images.githubusercontent.com/40846040/190718093-62bebd01-feff-4b1d-8c15-7f0bf392277a.png)

Upon launching the game, it immediately crashes due to this error:
```
[15:41:00] [pool-3-thread-1/ERROR]: Could not find parent net/minecraftforge/event/world/BlockEvent for class com/t2pellet/strawgolem/events/StrawGolemEvents$CropGrowthEvent in classloader cpw.mods.modlauncher.TransformingClassLoader@5961e92d on thread Thread[pool-3-thread-1,5,main]
[15:41:00] [pool-3-thread-1/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraftforge.event.world.BlockEvent
```
Log file: [latest.log](https://github.com/t2pellet/strawgolem/files/9586794/latest.log)

The CurseForge page comment section is filled with many people reporting the same issue of this crash.

It seems the Forge version of Straw Golem is being developed on a really old version of Forge that is now outdated and was before Forge's refactoring was done. Please try and change the dev environment to 1.19.2-43.1.2 Forge so you can detect and fix any issues due to Forge's refactoring.

**Comment by lapislui** [comment]
i also have same issue
