### ISSUE TITLE
Straw Golem Sound Issues

### ISSUE THREAD

**Issue by Darkosto** [t2pellet/strawgolem#112]
**Game Info**
Game Version : 1.18.2
Mod Version : 2.0.0b2
Mod Loader : Forge
Forge Version: 40.1.84

**Describe the bug**
There are a couple of sound issues I've been experiencing with the mod. I've tested both in a modpack and in an instance with Straw Golems and JEI only. 

There are 3 sound files in the assets folder that have issues, 2 of them have "bump" sounds and another is completely corrupted:

`strawgolem-ambience8` : Bump sound
`strawgolem-happy2` : Bump sound
`strawgolem-interest3`  : File distortion / corruption

The 2nd issue with the sound involves every other sound in the game becoming muted. I've done this with as few as 5 straw golems but it's easy to replicate with 50+. If you spawn a lot of Straw Golems in a small area, the game sounds begin to disappear and eventually stop altogether. A resource reload (F3+T) will not fix this and the only fix is to restart the entire client, but the issue will happen again.

![image](https://user-images.githubusercontent.com/10309699/201219335-2d1b5ff3-24f6-4815-a79b-d863250c7295.png)

After further inspection, it looks like the issue is being caused by the sound channels (shown in the f3 screen) begin to rise and neer drop back down. For reference, with no Straw Golems, my audio channels are between 0-10 consistently over long periods of time. With Straw Golems, this number will slowly rise and eventually max out the total audio that can happen in-game:

![image](https://user-images.githubusercontent.com/10309699/201219693-3cf30eb2-5bc8-4675-9f8f-b64ac8d5178f.png)

At this point `247/247` all sounds are gone.

**To Reproduce**

1. Spawn in a large number of Straw Golems
2. Wait (upwards of 3-5 minutes)
3. Sound will eventually be completely muted

Please let me know if I can provide any further information, thanks!
Darkosto

**Comment by Darkosto** [comment]
Okay, so I've looked further into this and have fixed it by creating a resource pack that removes all of the "corrupted" sound files. The following files would need to be replaced:

```
      "strawgolem:strawgolem-ambience7"
      "strawgolem:strawgolem-ambience8"
      "strawgolem:strawgolem-strain2"
      "strawgolem:strawgolem-damage2",
      "strawgolem:strawgolem-damage4"
      "strawgolem:strawgolem-happy2"
      "strawgolem:strawgolem-scared3"
      "strawgolem:strawgolem-interest3"
```


and `"strawgolem:strawgolem-disgusted"` does not have a sound file in the mod

Loading in this json file as your `sounds.json` and adding in a disgusted audio file will stop this issue from occurring:

```json
{
  "golem_ambient": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemAmbient",
    "replace": true,
    "sounds": [
      "strawgolem:strawgolem-ambience1",
      "strawgolem:strawgolem-ambience2",
      "strawgolem:strawgolem-ambience3",
      "strawgolem:strawgolem-ambience4",
      "strawgolem:strawgolem-ambience5",
      "strawgolem:strawgolem-ambience6",
      "strawgolem:strawgolem-ambience9"
    ]
  },
  "golem_strained": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemStrained",
    "replace": true,
    "sounds": ["strawgolem:strawgolem-strain1", "strawgolem:strawgolem-strain3"]
  },
  "golem_hurt": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemHurt",
    "replace": true,
    "sounds": [
      "strawgolem:strawgolem-damage1",
      "strawgolem:strawgolem-damage3",
      "strawgolem:strawgolem-damage5"
    ]
  },
  "golem_death": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemDeath",
    "replace": true,
    "sounds": ["strawgolem:strawgolem-death1", "strawgolem:strawgolem-death2"]
  },
  "golem_heal": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemHeal",
    "replace": true,
    "sounds": [
      "strawgolem:strawgolem-happy1",
      "strawgolem:strawgolem-happy3",
      "strawgolem:strawgolem-happy4"
    ]
  },
  "golem_scared": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemScared",
    "replace": true,
    "sounds": [
      "strawgolem:strawgolem-scared1",
      "strawgolem:strawgolem-scared2",
      "strawgolem:strawgolem-scared4"
    ]
  },
  "golem_interested": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemInterested",
    "replace": true,
    "sounds": [
      "strawgolem:strawgolem-interest1",
      "strawgolem:strawgolem-interest2"
    ]
  },
  "golem_disgusted": {
    "category": "neutral",
    "subtitle": "strawgolem.subtitle.golemDisgusted",
    "replace": true,
    "sounds": ["strawgolem:strawgolem-disgusted"]
  }
}
```

**Comment by Darkosto** [comment]
Sorry, one last issue regarding sounds: The strained sound is not localized for the captions:
![image](https://user-images.githubusercontent.com/10309699/201227719-90a2408d-41f0-4168-9b90-5b5cf52c1022.png)

**Comment by ejm554** [comment]
This is an excellent bug report!

**Comment by eyesoffaith** [comment]
I agree, this is expertly done. I understand that it may take some time for an official fix to come through but is there any chance a pre-made resource pack could be put together to resolve this @Darkosto. I'm having trouble creating the resource pack according to your instructions and would love to have this fix in 😁

**Comment by eyesoffaith** [comment]
Nevermind, I think I figured it out. I've built a resource pack to resolve the issue. I don't know how folks feel about posting files here so if you would prefer this is removed I am happy to remove it.
[StrawGolemSoundFix.zip](https://github.com/t2pellet/strawgolem/files/10149603/StrawGolemSoundFix.zip)

**Comment by t2pellet** [comment]
christ thats a great report, ty <3

it's fixed in my local branch, will be fixed in the next beta release (which I've finally began working on today)
