### ISSUE TITLE
Golem Loads as pig texture

### ISSUE THREAD

**Issue by JohnHadish** [t2pellet/strawgolem#116]
**Game Info**
Game Version : 1.19.2
Mod Version :  Strawgolem-fabric-1.19-2.0.0b2.jar
Mod Loader : Fabric
fabric-api-0.66.0

Other mods Installed on Server:
spark 1.9.45
sodium 1.18.2-0.4.4
phosphor 0.8.1
lithium 0.10.2
justplayer heads 2.5 
just mobheads 6.1
fabric-carpet 1.4.84+v221018
Dynmap 3.4
collective fabric 5.14
carpet extra 1.4.83

**Describe the bug**

Straw Golem Loads into Game with Texture of Pig. Appears to behave normally otherwise. Disappears on exiting game and reloading.

![2022-11-16_22 26 49](https://user-images.githubusercontent.com/35115540/202372519-9ba8a9b5-28f5-47c0-a095-80867bb71ae3.png)

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by t2pellet** [comment]
... I can't reproduce this for the life of me. It occurs all the time or just sometimes?

**Comment by JohnHadish** [comment]
It is always for everyone on my server. I have the feeling there is an incompatibility issue with one of the head mods, but I do not know for sure. You can close if no one else is having the same issue.

**Comment by t2pellet** [comment]
I`ll try and investigate, but will probably take me a while
