### ISSUE TITLE
How to actually config straw golem behavior??

### ISSUE THREAD

**Issue by Corpse405** [t2pellet/strawgolem#118]
Game Version : 1.16.5
Mod Version : 1.16-1.9
Mod Loader : Forge

In the documentation it says you can configure the Golems behavior so they don't get hungry or die. I might just be a boomer or something, but I cant figure out where I can configure the files. When I go to the mod menu the config button is greyed out. is there place on my computer i'm supposed to go instead? 

**Screenshots**
![Screenshot 2022-11-18 095734](https://user-images.githubusercontent.com/85843447/202750810-012187f2-817c-4797-a234-86538b10ed9b.jpg)

**Additional context**

**Comment by t2pellet** [comment]
1.16 version is deprecated. There's still a config file though, in the config folder.
