### ISSUE TITLE
Ticking World exception

### ISSUE THREAD

**Issue by katubug** [t2pellet/strawgolem#123]
**Game Info**
Game Version : 1.18.2
Mod Version : beta 3
Mod Loader : Forge 40.1.85

**Describe the bug**
Server crashed, seemingly out of the blue. Here is the report: https://pastebin.com/wyjVS7y0

**To Reproduce**
No idea, I'm sorry.

**Comment by t2pellet** [comment]
duplicate of https://github.com/t2pellet/strawgolem/issues/122
