### ISSUE TITLE
Game Crashing 

### ISSUE THREAD

**Issue by LadySunx** [t2pellet/strawgolem#126]
Modpack: Medieval MC [FABRIC] - MMC1 1.19.2 (Just in case you needed to know)

Below is the crash report
https://mclo.gs/fXZYiub

Sorry if I am at the wrong place to report if I am please let me know thank you.

**Comment by t2pellet** [comment]
They're using an outdated beta version of strawgolem.

Tell them to update. This is fixed in beta.4

**Comment by HipsterGumby** [comment]
I'm having the exact same issue with a custom fabric modpack 1.19.2

I tried to go update to beta.4 but it is not available. I can only see up to beta.3

I'm trying to build it in the curseforge app, any help would be amazing! I want to use this mod so bad!

**Comment by t2pellet** [comment]
https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn
https://www.curseforge.com/minecraft/mc-mods/straw-golem-reborn
![image](https://user-images.githubusercontent.com/4323034/209230073-aa4bb633-dbf6-471a-9092-0447e27f4404.png)

**Comment by HipsterGumby** [comment]
This is what I'm seeing, not sure if I am just doing it wrong or if I just need to do it from somewhere else.

![image](https://user-images.githubusercontent.com/107386246/209246102-41b1422a-4c04-4ca5-917a-ef19d56fdb66.png)

**Comment by t2pellet** [comment]
curseforge being dumb -- beta.3 shouldnt even be available for download anymore, i archived it.

I've made a small change in the file description hoping that'll prompt something on curseforges end, hopefully you can see it now?
