### ISSUE TITLE
the golem is not working properly and spamming an error in the server panel

### ISSUE THREAD

**Issue by papillo12** [t2pellet/strawgolem#129]
**Game Info**
Game Version : 1.19.2
Mod Version : strawgolem-1.19.2-2.0.0-beta.5
Mod Loader : Fabric

**Describe the bug**
The golem does not work very well and spams this error "[Server thread/ERROR]: Attempting to insert point outside of OctTree boundary "

**To Reproduce**
1. just by putting the golem to work, and the server spams the "[Server thread/ERROR]: Attempting to insert point outside of OctTree boundary "

**Screenshots**
![Captura de pantalla 2023-01-03 192649](https://user-images.githubusercontent.com/80440525/210467808-9abc2f8c-3f09-4729-9029-12d30e6fbaa1.png)

**Additional context**

[2023-01-03-5.log](https://github.com/t2pellet/strawgolem/files/10340826/2023-01-03-5.log)

**Comment by purejosh** [comment]
I second this. It may or may not also be causing some severe dips in TPS...

**Comment by JaboyKoral** [comment]
I am also having this problem, even after the golems decay and disappear.

**Comment by SneakyGhost142** [comment]
I am also having this problem on 1.19.2 beta5;
golems are just wandering without working and the server panel il full with that error

**Comment by Lozf** [comment]
I am having this problem on single player in 1.18.2 using forge 40.2.0, and using the most recent file.

**Comment by JordanCoteRNG** [comment]
I have the same error, the golem doesn't even try to work most of the time

**Comment by Flogah** [comment]
Having the same issue. Killing the golems also doesn't stop whatever keeps trying to insert points, just constant errors every 30 seconds or so.

**Comment by Bluewolf1942** [comment]
We were having an issue where the golems would pick up crops but then just stand there, but we found out that if you shift click the golem and then shift click the chest they will then work and deposit crops into the chest, they will also have issues accessing the chest if there is something placed above the chest like a hopper. Not sure if this is the same issue but hope this may help!

**Comment by t2pellet** [comment]
Should be fixed in new rewrite!
https://modrinth.com/mod/straw-golem

**Comment by lantheon-t** [comment]
Also have the same error on 1.18.2 forge 40.2.4. It will spam the server and then crash it.

**Comment by sergeycherepanov** [comment]
Any change to fix it for 1.18.2 version?

**Comment by t2pellet** [comment]
fixed in newest release for 1.19.2
