### ISSUE TITLE
golem wont spawn

### ISSUE THREAD

**Issue by ZeroThingz** [t2pellet/strawgolem#132]
**Game Info**
Game Version :1.19.2
Mod Version :1.19.2

Mod Loader : cursed forge

**Describe the bug**
They literly wont spawn i put the carved pumpkin on the straw golem adn they wont spawn
**To Reproduce**

**Screenshots**

**Additional context**

**Comment by antonhibl** [comment]
yeah I can confirm on fabric 1.19.2 the golem doesn't spawn with hay and a carved pumpkin. The only way to get it is to manually summon them with commands.

**Comment by snoopypoop** [comment]
May i ask what commands you are using? I have the same problem they wont spawn

**Comment by antonhibl** [comment]
@snoopypoop its /summon strawgolem:strawgolem or something similar.

**Comment by antonhibl** [comment]
Also just to add, neither of the fabric or the forge 1.19.2 versions actually let anything spawn. This definetely needs to be fixed or the mod is pretty much useless in the current state.

**Comment by HeartsofCourse** [comment]
I can confirm this is also the case in the 1.20.1 Fabric version
<img width="960" alt="Screenshot (189)" src="https://github.com/t2pellet/strawgolem/assets/39486231/f8916b88-c576-4668-97fb-b018cfdbf3e8">

**Comment by honeybrews** [comment]
Is this going to be fixed? I have players asking me about this! :)

**Comment by t2pellet** [comment]
this should be fixed in the newest release, lmk if not!
