### ISSUE TITLE
Golems just stand still after harvesting crops

### ISSUE THREAD

**Issue by gguy825** [t2pellet/strawgolem#133]
**Game Info**
Game Version : 1.19.2
Mod Version : strawgolem-1.19.2-2.0.0-beta.5
Mod Loader : fabric 0.14.19

**Describe the bug**
Spawning in golems they all collect a crop but they just stand still and don't deposit anything in the chests. I have to manually assign them to a chest. 

**Screenshots**
![2023-06-08_18 30 08](https://github.com/t2pellet/strawgolem/assets/41169055/ce722ad1-bb74-4b38-b784-ee8582b9497b)

**Additional context**

**Comment by leftbones** [comment]
Also having this issue, but on the Forge version.

**Comment by t2pellet** [comment]
Should be fixed in new rewrite (only for fabric currently)!
https://modrinth.com/mod/straw-golem

**Comment by t2pellet** [comment]
closing also bc its more or less the same as https://github.com/t2pellet/strawgolem/issues/127
