### ISSUE TITLE
Golems simply don't reap or plant.

### ISSUE THREAD

**Issue by Yuuzinhozi** [t2pellet/strawgolem#134]
Game Version : 1.19.2
Mod Version : beta.5
Forge version: 43.2.14

I did tests using /summon, and creating normally, and they simply don't harvest, at any time, and not once, i'm playing in a survivor game in a server, using a host by Exaroton with some others mods, but I think have no conflict.. what I do? 
![3213213](https://github.com/t2pellet/strawgolem/assets/145175473/f4d9a322-9db7-443c-8b87-c057f9921d2e)

**Comment by t2pellet** [comment]
duplicate
