### ISSUE TITLE
Can't launch on 1.20.2 due to missing geckolib3

### ISSUE THREAD

**Issue by nco2k** [t2pellet/strawgolem#135]
i have the latest geckolib-fabric-1.20.2-4.2.3.jar installed, but i cant launch the game due to missing geckolib3. afaik there is no geckolib3 for 1.20.2, only geckolib4.

> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Install geckolib3, any version.
> Unmet dependency listing:
> 	 - Mod 'Strawgolem' (strawgolem) 2.0.1-alpha requires any version of geckolib3, which is missing!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by t2pellet** [comment]
There is no 1.20.2 version of the mod. Its for 1.19.2

**Comment by t2pellet** [comment]
I will be updating to 1.20 in not too long though

**Comment by Ynaught** [comment]
> I will be updating to 1.20 in not too long though

So, what ever happened to that?
