### ISSUE TITLE
Sorry to Bug here (Forge version?)

### ISSUE THREAD

**Issue by SuperStefan97** [t2pellet/strawgolem#136]
Hi! Sorry to bug you here with this, but couldn't find your mod on CurseForge and didn't understood how to leave a comment on Modrinth (if it's possible even).

Would you develop a Forge or NeoForge version for 1.20+? (if so, could it be starting from 1.20.1?)

Again, sorry if this is not the best way to contact you. Sorry in advance.

**Comment by t2pellet** [comment]
I'm going to get forge working on 1.19.2 first, the blocker on it working is some stuff for my new library mod isn't working. Once that's fixed, I'll be able to release on Forge, and then once I port to 1.20 it'll be ported for forge as well.

Afterwards I'll be backporting to 1.18

**Comment by SuperStefan97** [comment]
Thank you!
