### ISSUE TITLE
[1.19.2] Straw Golems/TLib Server Crash

### ISSUE THREAD

**Issue by Buneez** [t2pellet/strawgolem#143]
Crash Log: https://pastebin.com/T6H0tcvf

Hello! I'm trying to make a modpack, and keep running into a mod loading error with TLib when running it in a server. 

I created a new instance with only Tenzin Lib, Straw Golems and GeckoLib (logs implied GeckoLib was required) and it launches in singleplayer, but keeps crashing in a server.

**Comment by devoh747** [comment]
They have turned off allowing it to be distributed..  as seen here.  Not sure why or when this happened.  Hopefully a bug.

![attachment](https://github.com/t2pellet/tlib/assets/14967866/347be216-7217-4441-b014-82dbfa752374)

https://api.curseforge.com/v1/mods/919468

This causes issues with https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn

**Comment by t2pellet** [comment]
Indeed, did not realize this was a setting, must have flipped it by accident 😅  - will take a look
