### ISSUE TITLE
Incompatibility with Quark Oddities Pipe

### ISSUE THREAD

**Issue by M1dnightRid3r** [t2pellet/strawgolem#15]
there is a problem between quark oddities mod and straw golem mod. My game keeps crashing whenever a straw golem tries to send a berry to a chest. I think the problem is that the golems try to send it to the pipes underground and not the chest because the pipes run right under them but my game keeps crashing everytime there is an interaction between the quark mod and the straw golem mod.

**Comment by t2pellet** [comment]
Thanks for the report! I'll see what I can do

**Comment by t2pellet** [comment]
Should be fixed in a4!
