### ISSUE TITLE
Incompatibility with new forge versions

### ISSUE THREAD

**Issue by yetshadow** [t2pellet/strawgolem#16]
Hi, there is a problem when loading the mod with some of the recent forge updates. Something with the fly particles.

**Comment by t2pellet** [comment]
Thanks. That explains some of the comments I've been getting on curse. 

Mind telling me which version broke it?

**Comment by t2pellet** [comment]
It's not my mods' fault. It's immersive engineering.

https://github.com/BluSunrize/ImmersiveEngineering/issues/4410

Use Forge 31.4.25.
