### ISSUE TITLE
1.16-1.9 Crash on startup with Immersive Engineering

### ISSUE THREAD

**Issue by Spudli** [t2pellet/strawgolem#18]
I get this crash log on startup with Immersive Engineering:

The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle strawgolem:fly
Exit Code: -1

https://pastebin.com/5tcXXrHR

**Comment by Spudli** [comment]
I see someone else mentioned the fly particle issue, what "older" version of forge is recommended for 1.16.3?

**Comment by t2pellet** [comment]
Mod needs to be patched for 1.16.3, best to use 1.16.2 for now

Sorry about that!

**Comment by t2pellet** [comment]
Turns out this doesn't seem to be my fault, but IE's
https://github.com/BluSunrize/ImmersiveEngineering/issues/4410
