### ISSUE TITLE
Corrupted World

### ISSUE THREAD

**Issue by ProfessorBustanut** [t2pellet/strawgolem#19]
placed 4 straw golems 
noticed they decay 
changed the config to disable 
world crashes on open

**Comment by ProfessorBustanut** [comment]
removed mod
still crashes

**Comment by ProfessorBustanut** [comment]
fixed by useing Amulet(alternate mcedit)to delete the area

**Comment by t2pellet** [comment]
Can you please give me a crash report.

I can't help or do anything without that.

**Comment by ProfessorBustanut** [comment]
ok i tryed to replicate it but it wont crash so idk what happened the first time
