### ISSUE TITLE
instant rot

### ISSUE THREAD

**Issue by ProfessorBustanut** [t2pellet/strawgolem#20]
setting the config lifespan to -1 instantly rots the golem on spawn
healing the golem with wheat makes them pretty again but they die the next day anyway

**Comment by t2pellet** [comment]
You have to feed them wheat often! I have a fix coming for the -1 issue though.

Thanks!

**Comment by t2pellet** [comment]
Fixed in 82ff60fe63694216a0a13d4db2f199728b6e6fc2
