### ISSUE TITLE
golems disappearing when the lifespan in config is set to -1.

### ISSUE THREAD

**Issue by TerranE5** [t2pellet/strawgolem#22]
Ok, this bug has been bothering me for a while. 
So, I found this bug when I set the configuration of their lifespan to -1.

Then after that, I began testing it on my new world that I created. 
One thing I noticed after playing this mod is that if you create a straw golem, leave them for a while then come back to check on them, they will disappear after a certain amount of time has passed. 

Now before you type that "you need to build a fence around them" stuff- yes, I did. But they still disappeared. This bug can be executed by building a fence around the base, spawn a straw golem, leave the straw golem and after a while. Wait for it to disappear.

This is ONE of the bug that I found so far.

**Comment by t2pellet** [comment]
https://github.com/t2pellet/strawgolem/issues/20

Already reported, already fixed in the latest commit (82ff60fe63694216a0a13d4db2f199728b6e6fc2), just hasn't made it into a release yet!

I'll get new updates out soon, just working on a fabric port first
