### ISSUE TITLE
Fabric Server Issues

### ISSUE THREAD

**Issue by MusicalTester63** [t2pellet/strawgolem#27]
[crash-2021-02-25_11.29.54-server.txt](https://github.com/t2pellet/strawgolem/files/6048264/crash-2021-02-25_11.29.54-server.txt)
[crash-2021-02-25_11.25.27-server.txt](https://github.com/t2pellet/strawgolem/files/6048265/crash-2021-02-25_11.25.27-server.txt)

Whenever i place any block while having straw golem installed on my server it just crashes.

**Comment by t2pellet** [comment]
Issue has been identified - Fix will come soon! Sorry for the late reply, been busy.

**Comment by MusicalTester63** [comment]
It's okay I understand. Looking forward to the update!

**Comment by t2pellet** [comment]
I'm really sorry for this - it was honestly a really really stupid oversight on my part, using a client only method.

Although I did check running a server in IDE, but maybe client methods are still available for some reason there.

This type of thing will never happen again, I promise!

Here is a fixed version so you don't have to wait for the next release!

Just let me know to verify that it works, I'm on the train rn and only on my laptop - so I couldn't run a server to check

**Comment by MusicalTester63** [comment]
I'm sorry to say this but my server won't even start with it. Maybe this screenshot could help you solve the problem because I have no idea what's going on
![image](https://user-images.githubusercontent.com/79689839/110213387-1bba6680-7ea0-11eb-8b84-daac4b49bd6e.png)

**Comment by t2pellet** [comment]
Something's screwed up with the way i rewrote my networking packets to work. Looking at it now

**Comment by t2pellet** [comment]
Fixes this particular issue on my machine.

Something about the sounds is off in my installation though, the client persistently gets errors when on a dedicated server (doesn't crash though)

Not sure if the particle effects from interacting with the golem are working either on a dedicated server (although they might be - I didnt check this thoroughly)

**Comment by MusicalTester63** [comment]
Good news! It doesn't crash and it seems like it's not outputting any errors either. Great work.
![2021-03-09_08 14 10](https://user-images.githubusercontent.com/79689839/110432649-b0df7a00-80af-11eb-88fe-effaef79fd8d.png)

**Comment by MusicalTester63** [comment]
Another 2 straw golem related crashes.

[crash-2021-03-09_23.27.36-server.txt](https://github.com/t2pellet/strawgolem/files/6114697/crash-2021-03-09_23.27.36-server.txt)
[crash-2021-03-09_23.18.07-server.txt](https://github.com/t2pellet/strawgolem/files/6114698/crash-2021-03-09_23.18.07-server.txt)

**Comment by t2pellet** [comment]
[fix.zip](https://github.com/t2pellet/strawgolem/files/6166284/fix.zip)

Should fix those.

**Comment by t2pellet** [comment]
Closed due to inactivity
