### ISSUE TITLE
Golems only harvest some of the crops in Pam's Harvestcraft

### ISSUE THREAD

**Issue by xXShadowmayXx** [t2pellet/strawgolem#30]
They harvest all of the grapes and veggies, but it seems like the only things they can't harvest seems to be grains. The crops I have gotten in my survival world that they don't touch are quinoa, rye, rice, and cotton. There may be more, but as far as I know those are the ones they seem not to pick up.

**Comment by t2pellet** [comment]
There is a mod compat thread for stuff like this. Post this there.
