### ISSUE TITLE
Golem Harvest AI Issues on Fabric Indev

### ISSUE THREAD

**Issue by hugeblank** [t2pellet/strawgolem#38]
Built the mod from the latest commit (3b338b6b79d00229895be4f9e10eb90eec80cfbd) as the one on CF was crashing my server. 

It seems that the harvest crop goal is flawed in some way that golems will not perform any action to do with their purpose, aside from pouting and looking cute. They do not harvest crops, they do not grab items, and they do not seem to care for chests. 

I think this possibly has to do with how you're checking for registered crop blocks - with the assumption that all of the blocks are registered when your mod initializes. I had the same issue with a "simple harvest" mod I was working on and after some discussion someone in the fabric discord spotted me [some code](https://github.com/hugeblank/Harvest/blob/main/src/main/java/info/tehnut/harvest/RegistryWaiter.java) to handle waiting for all blocks. This waits for specific identifiers but I'm sure it could be adapted to check for instances of specific classes (`CropBlock`, etc.). You can check out the sample use of it [here](https://github.com/hugeblank/Harvest/blob/5e73fd2a92d871836e967d0bdc39598e45d71583/src/main/java/info/tehnut/harvest/Crop.java#L23-L32)

This assessment was just at a glance however, take it with a grain of salt.

**Comment by t2pellet** [comment]
Golems pout when they're hungry. feed them an apple. I believe this is documented on the curseforge page

If you're building from the latest commit, then yea, things are WIP. I make releases when I feel something is stable enough.
Please don't open tickets for unfinished/WIP features, I'm well aware that they're unfinished/WIP.

**Comment by t2pellet** [comment]
Vanilla crops are being harvested now
