### ISSUE TITLE
Fabric Server Crashed on Start Up After Mod Implementation

### ISSUE THREAD

**Issue by curlost** [t2pellet/strawgolem#39]
Quite frankly it's a lot, and I can't seem to be able to grab the exact thing from the system or decipher what exactly is causing the crash? It worked on a single player world just fine, no problems, but the moment I dropped the mod into a server and ran it it crashed, any ideas what would cause such a problem? I'll include a screenshot of all the mods included in the server pack.
edit: Log for latest run also included

![mods 5_25_2021 11_23_32 AM](https://user-images.githubusercontent.com/84805976/119549036-ae55fd80-bd4b-11eb-803f-c9c5b4f2dc4d.png)

![latest - Notepad 5_25_2021 11_29_23 AM](https://user-images.githubusercontent.com/84805976/119549858-887d2880-bd4c-11eb-99eb-c3f801d81eb1.png)

**Comment by t2pellet** [comment]
https://github.com/t2pellet/strawgolem/issues/27
