### ISSUE TITLE
Please, I'm begging. I'm on my knees. I need my little guys in 1.17.1!

### ISSUE THREAD

**Issue by AutumnWHM** [t2pellet/strawgolem#47]
I'm getting desperate. My little boys. My baby guys. I need them, but my modded server depends on 1.17.1. I'm writhing on the ground, occasionally thrashing about in fits of choleric despondency. My little baby straw MEN. My guys...

**Comment by t2pellet** [comment]
Closing, see https://github.com/t2pellet/strawgolem/issues/44

(In the works 😁  )
