### ISSUE TITLE
[Forge] -1 not setting lifespan infinite 

### ISSUE THREAD

**Issue by SAwesome1018** [t2pellet/strawgolem#48]
title says it all, when the lifespan is set to -1 in the config the golems still die eventually

**Comment by Nupper** [comment]
i concur. I tried to give the straw golems wheat to feed them because they where bugging out and they died.

**Comment by sysyss** [comment]
in fact, if you lifespan set -1 and feed wheat than golem will die or they not die. i think they work like bedrocks hardness. if life is under zero, than they stop time-gone

**Comment by SAwesome1018** [comment]
> i concur. I tried to give the straw golems wheat to feed them because they where bugging out and they died.



> in fact, if you lifespan set -1 and feed wheat than golem will die, Or not feed they will not die. i think they work like bedrocks hardness. if life is under zero, than they stop time-gone

the way i got around this is by just using /summon strawgolem ~ ~ ~ {Invulnerable:1}
(might have to mess around with the command)
this makes it so nothing outside of a player in creative mode can kill them

**Comment by sysyss** [comment]
i think real problem is, why full-hearty golem is look dirt and eat wheat

**Comment by LyrasaurusRose** [comment]
1.16.5 version - setting config to lifespan of -1 causes the straw golems to instantly rot.  Not sure if they'll eventually die (didn't wait that long) but expected behavior is just, not having them rot instantly.
