### ISSUE TITLE
Wrong use description on curseforge

### ISSUE THREAD

**Issue by Thrywyn** [t2pellet/strawgolem#51]
https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn
In the description of the Forge edition, it is stated:
Can specify which container to deliver by shift right clicking golem and then container with an empty hand

This does not work, and you have to hold wheat for it to obey you. Text, or ingame mechanics need to be updated.

**Comment by ejm554** [comment]
Just to confirm, are you saying that on Forge, you need to right-click while holding wheat, whereas on Fabric, you do the same thing, but with an empty hand?

**Comment by Thrywyn** [comment]
> Just to confirm, are you saying that on Forge, you need to right-click while holding wheat, whereas on Fabric, you do the same thing, but with an empty hand?

Yes

**Comment by ejm554** [comment]
> [...] In the description of the Forge edition, it is stated: 
> "Can specify which container to deliver by shift right clicking golem and then container with an empty hand"
> This does not work, and you have to hold wheat for it to obey you. Text, or ingame mechanics need to be updated.

@Thrywyn :: In an effort to address your issue, I made a pull request (https://github.com/t2pellet/strawgolem/pull/71), which updates the Read Me on this GitHub repository. I'm not sure if/how a volunteer like me can the CurseForge page, but hopefully my PR is a small improvement.
