### ISSUE TITLE
[Fabric] Straw Golems shaking with & without items - AI breakage

### ISSUE THREAD

**Issue by Cakemoth** [t2pellet/strawgolem#61]
Threw this mod onto Better Minecraft [FABRIC]. Noticed that they do farm; however, they tend to lock up and start shaking very hard. 
I left them there for a bit to see what would happen, nothing changed. They can enter this state from what I can tell at any moment, and no; they aren't hungry. 

They will deliver stuff, but from what I have seen while watching/leaving them - they will not deliver the items they're holding once they start shaking. They'll follow you with the apple in hand, some wont, they will turn to look at you whether holding items or not. 

Does Serene Seasons affect them? Are they impeded by weather, as they tend to sit around lazily vs actually farming if they aren't bugged out.

**Comment by t2pellet** [comment]
Shaking occurs when they're cold or in the rain as well, is that what you're observing? They should still do their thing though, their lifespan will just tick down faster.
