### ISSUE TITLE
[Fabric] [1.17.1] [1.10-beta-5] Ironic Deaths

### ISSUE THREAD

**Issue by Venaf** [t2pellet/strawgolem#63]
I keep finding loose wheat in my pumpkin patch and I believe it's from pumpkins growing and suffocating the golems. Is it possible to turn off suffocation or shunt them outside growing melon-type blocks? Or just a way to generally make the patches safe for them?  I also notice they're very hit or miss on harvesting the pumpkins at all, and delivering them after harvest, though delivery issue seems to be them stopping just short of their reach when heading to the chest - a small nudge towards it and they put their block away.

**Comment by t2pellet** [comment]
Fixed with latest alpha (2.0.0a4). Sorry it took me forever!
