### ISSUE TITLE
[Fabric] [1.17.1] [1.10-beta-5] Server stalls when setting hunger in config to -1

### ISSUE THREAD

**Issue by Venaf** [t2pellet/strawgolem#64]
Here is my [config](https://pastebin.com/dPeJFPgS), when I load the world I very briefly hear sounds from existing creatures (I was standing by my chicken farm) but less than a second in everything stops and I can't interact with anything.  The game doesn't crash and I don't get any log entries at all, nor does the world save after that point.  If I set hunger back to default, the game runs fine.

**Comment by t2pellet** [comment]
Should be fixed with the latest commit. 

Here's a build to try (for fabric 1.18.2)
[test.zip](https://github.com/t2pellet/strawgolem/files/8694425/test.zip)
