### ISSUE TITLE
Incompatibility With Croptopia 1.6.2 Through 1.7.2

### ISSUE THREAD

**Issue by SalvieMundi** [t2pellet/strawgolem#68]
Something about this mod (my bets are on [this mixin](https://github.com/t2pellet/strawgolem/blob/master/src/main/java/com/commodorethrawn/strawgolem/mixin/GrowthMixin.java)) is causing Croptopia trees to lag the server to the point where the server shuts down due to one tick taking over 60 seconds. See [issue #268](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/268) on the Croptopia issue tracker.

To reproduce: 
1. Put this mod and Croptopia together.
2. Plant any Croptopia sapling other than Cinnamon
3. Bonemeal
4. 99% chance the server just hangs and then shuts down after 60 seconds

**Comment by SalvieMundi** [comment]
putting the following into the config's blacklist works as a stopgap solution, but there is probably a better one in code.

blacklist = [croptopia:apple_crop,croptopia:banana_crop,croptopia:orange_crop,croptopia:persimmon_crop,croptopia:plum_crop,croptopia:cherry_crop,croptopia:lemon_crop,croptopia:grapefruit_crop,croptopia:kumquat_crop,croptopia:peach_crop,croptopia:coconut_crop,croptopia:nutmeg_crop,croptopia:fig_crop,croptopia:nectarine_crop,croptopia:mango_crop,croptopia:dragonfruit_crop,croptopia:starfruit_crop,croptopia:avocado_crop,croptopia:apricot_crop,croptopia:pear_crop,croptopia:lime_crop,croptopia:date_crop,croptopia:almond_crop,croptopia:cashew_crop,croptopia:pecan_crop,croptopia:walnut_crop]

**Comment by t2pellet** [comment]
Fixed with latest alpha (2.0.0a4)

Sorry it took me so long!!
