### ISSUE TITLE
Curseforge page incorrect

### ISSUE THREAD

**Issue by astynax777** [t2pellet/strawgolem#69]
On the [curseforge page](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn?page=8) it states 
"Can specify which container to deliver by shift right clicking golem and then container with an empty hand"
I had to search through the issues on here to determine that you needed wheat in your hand to order them.

**Comment by ejm554** [comment]
Can you reference the specific GitHub issue that states the thing about wheat?
