### ISSUE TITLE
Golem harvest crops but does not put them in chest with Pam's HarvestCraft 2 - Crops

### ISSUE THREAD

**Issue by midnightangelwing** [t2pellet/strawgolem#70]
using 1.16.5 & the strawgolem-1.16-1.9 in forge. I was testing this mod for a pack I'm trying to build. It worked with all mod except for Pam's HarvestCraft 2 - Crops. there are  23 crops that get harvested but are not picked up & put in the chest. There are no drop from the harvest when the golem harvest it.  The rest of 53 out 77 crops work fine with the straw golem mod. Is there a way for me to fix this in config?

**Comment by itsdinkd** [comment]
Same with croptopia
