### ISSUE TITLE
Start a Straw Golem wiki

### ISSUE THREAD

**Issue by ejm554** [t2pellet/strawgolem#72]
I'd love to see a wiki for this mod, and I'd be willing to contribute to it. (Add a comment if you're also willing!)

As part of this request, I'd like the wiki to have a means for the public to create new pages and/or edit content. In other words, let non-developers contribute, even if the devs play the role as moderator. 

I think a wiki would be a useful place to dive into details about the different flavors of the mod. 

I could envision the wiki being in one of the following places:
- This GitHub repository 
- A generic wiki built with MediaWiki
- A Fandom wiki

I _don't_ think CurseForge would be a good choice for the wiki since there are two sites there for this mod, i.e., Fabric and Forge. A single wiki, IMO, should encompass both versions.

**Comment by t2pellet** [comment]
I’m amenable to that.

It’s worth noting I’m working on a 1.18 port that will unify both versions, so going forward, once that is done there should always be parity going forward.

**Comment by ejm554** [comment]
> I’m amenable to that.

Cool. What's the next step? 

- Maybe re/enable he Wiki on this repository? It seems to be [disabled](https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis) or something; when I click on the Wiki button, I'm re-directed to Code page. 
- If you prefer the generic MediaWiki, or the corporate one, LMK, and I can research it.

**Comment by t2pellet** [comment]
Should be enabled, feel free to reopen if its not.
