### ISSUE TITLE
Complaint about your curseforge page

### ISSUE THREAD

**Issue by Jamiebear** [t2pellet/strawgolem#75]
Because you copied another mod all right reserve is nonsense the license would be MIT the same as the original mod

**Comment by t2pellet** [comment]
Firstly, this isn't a copy, its a spiritual successor that started as a fork.

Secondly, no, that's not how the MIT license works.

Take a look at this excerpt:

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions...

**Comment by Jamiebear** [comment]
So that means anyone can make a straw golem mod as you do not own the rights to it

**Comment by t2pellet** [comment]
No, lmao, thats the MIT license of the original mod.

The takeaway is that I was well within my rights to use the original mod in making my own, which I'm free to distribute under whatever license I want.

Yes, you could make your own strawgolem mod, but only using assets from the original MIT-licensed project, and not from this one.
