### ISSUE TITLE
[Question] BlockEntity Based Crops

### ISSUE THREAD

**Issue by InfinityRaider** [t2pellet/strawgolem#76]
Hello,

I have been following the development of your mod from a distance, as I wanted to implement compat with my mod as well (I had made a [PR](https://github.com/t2pellet/strawgolem/pull/37) for this a while ago).

In the meantime, I have noticed you have implemented support for BlockEntity based crops, the entry point for which, I believe, happens [here](https://github.com/t2pellet/strawgolem/blob/master/Common/src/main/java/com/t2pellet/strawgolem/crop/CropRegistry.java#L23)?

Although it is a good thing that you were mindful of BlockEntity based crops, it is a bit of a problem that it still requires a Block property for the age of the crops, which is not guaranteed for BlockEntity based crops (in fact, mine don't, as it would be redundant, and basically impossible as well).

Therefore, my question is, are you planning to expand upon this?
And if not, would you mind if I drafted up a PR instead?

**Comment by t2pellet** [comment]
Made some changes yesterday that might help. if not, feel free to draft up a PR.

**Comment by InfinityRaider** [comment]
Thanks for taking the time and effort to look into this.
This is indeed a big step forward.
As a followup question, is there a way to tell the golem they should right click the crop instead of breaking it?

**Comment by t2pellet** [comment]
Pushed up another commit that I think should help with that?

**Comment by InfinityRaider** [comment]
Hello again,

Would it be possible to push out a build on CurseForge containing these commits?
I am asking, as I am using cursemaven to add the build to my dev environment, and the current version on CurseForge does not have these changes it seems?
Unless you are hosting a maven repo somewhere I could grab the artefacts from instead?

**Comment by InfinityRaider** [comment]
Actually, some changes might be necessary, I think it would be better to register a BlockEntityType instead of a BlockEntity, as the type is a registered constant, the BlockEntities themselves are volatile objects.
Using them like this risks causing memory leaks

**Comment by t2pellet** [comment]
Hey! Should have build up on CurseForge with the changes by EOW. I don't have my own maven repo set up, at least not yet :)

**Comment by InfinityRaider** [comment]
Thanks, no worries.
Could I get a poke when you put out a build with these changes? Thanks!

**Comment by t2pellet** [comment]
@InfinityRaider Build has been uploaded and is under review!

**Comment by InfinityRaider** [comment]
Compat implemented: https://github.com/AgriCraft/AgriCraft/commit/b8c10a948528a06bf1dec805fb6cc5c6a02819ca
Thanks for the cooperation!

**Comment by t2pellet** [comment]
Sweet! Glad I could help :)
