### ISSUE TITLE
Straw Golem's stop working after about one in game day

### ISSUE THREAD

**Issue by Galwion** [t2pellet/strawgolem#78]
Game Version : 1.18.2
Mod Version : 2.0.0a2
Mod Loader : Forge Version: 40.1.19. Installed with CurseForge.

After creating a Straw Golem and assigning a Chest, it stops working after about one in game day. It's not hungry, so it's not sitting, just standing idle.

Thank you very much for your awesome mod and best of luck to you.

**Comment by t2pellet** [comment]
Should be fixed in latest curseforge release (2.0.0a3). Please reopen if it isn't
