### ISSUE TITLE
Server crash / lock

### ISSUE THREAD

**Issue by MaxWasUnavailable** [t2pellet/strawgolem#82]
**Game Info**
Game Version : 1.18.2
Mod Version : Latest alpha for 1.18.2
Mod Loader : Forge 40.1.22

**Describe the bug**
Server crashes after bonemealing (or naturally growing) a fruit tree.

**To Reproduce**

1. Place fruit tree sapling.
2. Bonemeal.
3. Server locks up entirely.
4. Notice Straw Golem logs as final logged entries. (Consistently does this)

**Screenshots**
![image](https://user-images.githubusercontent.com/89798523/169726518-1ead6788-2f85-4e4f-91b3-7a0fbc5d1e33.png)

**Comment by t2pellet** [comment]
Should be fixed in latest curseforge release (2.0.0a3). Please reopen if it isn't
