### ISSUE TITLE
Golem not summoning

### ISSUE THREAD

**Issue by HoodBlah** [t2pellet/strawgolem#87]
**Game Info**
Game Version : 1.18.2
Mod Version : 2.0.0a.3
Mod Loader : Forge 40.1.30

**Describe the bug**
Golem does not appear

**To Reproduce**

1. Place hay
2. Place carved pumpkin on top
3. Golem is not summoned

**Screenshots**
![416E335E-0A6F-42DB-9EFC-40616DFF2F00](https://user-images.githubusercontent.com/89415523/172715614-4937752d-b8f3-4b6c-9840-3de0b4d9ea1b.jpeg)

**Comment by t2pellet** [comment]
Can you send me a screenshot of your config file?

**Comment by HoodBlah** [comment]
![image](https://user-images.githubusercontent.com/89415523/172894670-5cefb4f8-650f-4281-af19-c483521a767b.png)
I think this is it, don't even know how it got disabled...

**Comment by t2pellet** [comment]
Yeah, bug in the current version, default is set to disabled. Already fixed in the repo, should have a quick hotfix release published by EOD

**Comment by HoodBlah** [comment]
Thank you! Also, when the golem opens the chest, the sound is a bit glitched. Like is sounds as if multiple chests are being opened at once and it is louder than normal.
