### ISSUE TITLE
harvest bug

### ISSUE THREAD

**Issue by gog1071** [t2pellet/strawgolem#89]
**Game Info**
Game Version : 1.18.2
Mod Version : 2.0.0b1
Mod Loader : fabric 0.14.8

**Describe the bug**
Golems won't do anything if there are 2 or more containers in their harvesting range

**To Reproduce**

1. create a farming field size 9x9, 1 water source block in the middle and plant something
2. create about 10 golems 
3. place 2 or more containers in their harvesting range
4. their harvesting tasks slowed down in someway, and the they just put stuff into only one chest. when it fully filled, they drop stuff on the ground without putting it into the other chests

**Comment by t2pellet** [comment]
To clarify, they're still harvesting, and are just putting it on the ground by their chosen container?

If yes, that's the designed behaviour. Once golems deliver to a chest, that becomes their "chosen" one. Either keep the chest from filling up, or manually direct them to other chests (chests are assigned by shift + rclick on a golem, and then a chest)

**Comment by gog1071** [comment]
ohh. i see. 
But when i place the 2nd chest, most of them change to wandering stage or something like that. and they will get back to work if i destroy a chest

**Comment by t2pellet** [comment]
could be the chest was obscuring their vision - LOS issues like that should be fixed with the newest release
