### ISSUE TITLE
Straw Golem Only Farms Carrots

### ISSUE THREAD

**Issue by LuminousFrost** [t2pellet/strawgolem#91]
Game Version : 1.18.2
Mod Version : 2.0.0.b1
Mod Loader : Forge 40.1.52

The straw golem seems to only want to farm carrots. The farm is full of diverse crops but it seems to only pick up and deliver the carrots to the barrel I have set for it. I read through some of the other issues to see if one was similar but didn't find it if there was one. One suggested that there were too many storage containers within the golems radius so I removed the extra containers but this didnt do anything. My mod list includes: 
-Alex's Delight
-Alex's Mobs
-Carry On
-Corpse
-Create 0.4
-Cultural Delights
-Farmer's Delight
-Farmer's Respite
-Nether's Delight
-Serene Seasons
-Supplementaries
-Survive
-Wildberries

Even if I cant get the issue fixed I'm keeping the mod because they are cute.

**Comment by t2pellet** [comment]
Definitely can’t reproduce this one, at least not with just strawgolen & farmers delight, and I don’t see why additional crops would cause this

have you fiddled with the config settings at all?

What crops does it seem to be ignoring?

**Comment by LuminousFrost** [comment]
Initially I had messed with the configs but ran into this issue. I deleted the config and reinstalled for a fresh one but that didn't work either. It ignores everything except carrots. Initially I thought it was only ignoring the mod ones but it is ignoring potatoes and melons as well. I'm including screenshots of the farm incase there's an issue with the setup.
![2022-06-21_08 09 11](https://user-images.githubusercontent.com/107939291/174834321-0cf24393-ce9a-4b7d-b01a-b62d4c14b2d5.png)
![2022-06-21_08 09 26](https://user-images.githubusercontent.com/107939291/174834352-f7e9ad9a-c89a-45cd-9c92-d726f48c5d83.png)

**Comment by t2pellet** [comment]
Are you able to produce this on a world with just strawgolem?

Definitely scratching my head at this one.

Also, maybe try giving this build a whirl (in case something wacky is going on with b1)
https://github.com/t2pellet/strawgolem/actions/runs/2532783872

**Comment by LuminousFrost** [comment]
The fresh world with only straw golem seemed to work fine. Currently waiting for a pumpkin to grow in my normal world since the golem died while I was afk. Broke all the plants and will replant after spawning the golem and will update when that happens.

**Comment by LuminousFrost** [comment]
They will pick up the vanilla (except sweetberries) and farmers delight ones now. The cultural delights and wildberries are still ignored though.

**Comment by t2pellet** [comment]
Probably a mod compat thing for cultural delights and wildberries, surprised to see sweetberries don't work, they always seem to harvest them without a problem for me.

I'll look into it.

**Comment by t2pellet** [comment]
One thing to note that might be posing as an issue is that the golems always try to harvest the closest grown crop. Its possible thats why they were so heavily favouring your carrots, if they were the closest to the bin.

**Comment by t2pellet** [comment]
Definitely can't reproduce them not harvesting sweet berries:
![2022-06-22_20 50 14](https://user-images.githubusercontent.com/4323034/175184315-39843f3b-68fd-4386-b02a-d47f4b6fed7f.png)
