### ISSUE TITLE
Can't Create Golem

### ISSUE THREAD

**Issue by Bluemagelord** [t2pellet/strawgolem#99]
Hi. 

I'm playing in 1.18.2 and when I smack the hay bale with the carved pumpkin - nothing happens. I can't get the golem to appear. 

I've tried it in survival / creative and can't seem to conjure the little guy. 

No errors were mentioned and the game didn't crash - it just didn't appear.

Thoughts?

**Comment by t2pellet** [comment]
Should be fixed in latest curseforge release
